import { closeSync, createWriteStream, existsSync, openSync, readFileSync, readSync, statSync, writeFileSync } from "node:fs"

/**
 * Random-access store for node body text, keyed by graph node id.
 *
 * HydraDB Cloud is memory-resident: a full-corpus load with document bodies
 * stored as node properties exhausted the instance's `maxmemory` at ~54% of the
 * corpus (every write then failing with "OOM command not allowed"). Body text is
 * the bulk of those bytes and the part the graph never queries — no Cypher Graf
 * issues filters, joins or matches on a document's body, it only reads it back
 * out to show as evidence. So bodies live here instead, and the graph keeps the
 * structure it actually traverses: ids, labels, titles, dsids, dates, edges.
 *
 * This is the same class of local sidecar as the vector index (same directory,
 * same lifecycle, regenerated by the same ingest), which is why it lives in this
 * package: both exist because the graph engine can't hold something, and both
 * are keyed by graph node id.
 *
 * Layout is two files beside the descriptor:
 *   `<base>.content.jsonl` — one `{id, text}` record per line, in write order
 *   `<base>.content.idx`   — id/offset/length triples, sorted by id
 *
 * The index is small enough to hold in memory (~15 MB per million records) while
 * the data file — several GB at full corpus — is never loaded: a lookup binary
 * searches the index and reads only that record's byte range. That keeps the web
 * app's resident memory flat regardless of corpus size, which matters because it
 * already carries a multi-GB vector index.
 */

export function contentStorePaths(basePath: string): { dataPath: string; indexPath: string } {
  const base = basePath.replace(/\.json$/, "")
  return { dataPath: `${base}.content.jsonl`, indexPath: `${base}.content.idx` }
}

/**
 * Streaming writer. Offsets are recorded as records are appended rather than by
 * re-reading the finished file, so building the index costs nothing beyond a
 * sort at close.
 */
export class ContentStoreWriter {
  private readonly dataPath: string
  private readonly indexPath: string
  private readonly stream: ReturnType<typeof createWriteStream>
  private ids: number[] = []
  private offsets: number[] = []
  private lengths: number[] = []
  private cursor = 0

  constructor(basePath: string) {
    const paths = contentStorePaths(basePath)
    this.dataPath = paths.dataPath
    this.indexPath = paths.indexPath
    this.stream = createWriteStream(this.dataPath, { flags: "w" })
  }

  /** Returns a promise only when the stream needs draining, so callers can honour backpressure without awaiting every line. */
  append(id: number, text: string): Promise<void> | undefined {
    const line = `${JSON.stringify({ id, text })}\n`
    const bytes = Buffer.byteLength(line)
    this.ids.push(id)
    this.offsets.push(this.cursor)
    this.lengths.push(bytes)
    this.cursor += bytes
    if (!this.stream.write(line)) {
      return new Promise((resolve) => this.stream.once("drain", () => resolve()))
    }
    return undefined
  }

  get size(): number {
    return this.ids.length
  }

  async close(): Promise<void> {
    await new Promise<void>((resolve, reject) => {
      this.stream.end((err?: Error | null) => (err ? reject(err) : resolve()))
    })

    // Sort by id so lookups can binary search. Ids are content-addressed hashes,
    // so append order is effectively random.
    const order = Array.from(this.ids.keys()).sort((a, b) => this.ids[a]! - this.ids[b]!)
    const count = order.length
    const buffer = Buffer.alloc(8 + count * 20)
    buffer.writeDoubleLE(count, 0)
    let cursor = 8
    for (const i of order) {
      buffer.writeDoubleLE(this.ids[i]!, cursor)
      buffer.writeDoubleLE(this.offsets[i]!, cursor + 8)
      buffer.writeUInt32LE(this.lengths[i]!, cursor + 16)
      cursor += 20
    }
    writeFileSync(this.indexPath, buffer)
  }
}

export class ContentStore {
  private ids: Float64Array = new Float64Array(0)
  private offsets: Float64Array = new Float64Array(0)
  private lengths: Uint32Array = new Uint32Array(0)
  private fd: number | undefined

  /** Returns false when no store exists at this path, so callers can degrade to graph-only properties. */
  load(basePath: string): boolean {
    const { dataPath, indexPath } = contentStorePaths(basePath)
    if (!existsSync(dataPath) || !existsSync(indexPath)) return false

    const buffer = readFileSync(indexPath)
    const count = buffer.readDoubleLE(0)
    // A truncated index (killed mid-write) would otherwise read garbage offsets
    // and return other records' text under the wrong ids.
    const usable = Math.min(count, Math.floor((buffer.length - 8) / 20))
    this.ids = new Float64Array(usable)
    this.offsets = new Float64Array(usable)
    this.lengths = new Uint32Array(usable)
    for (let i = 0; i < usable; i++) {
      const at = 8 + i * 20
      this.ids[i] = buffer.readDoubleLE(at)
      this.offsets[i] = buffer.readDoubleLE(at + 8)
      this.lengths[i] = buffer.readUInt32LE(at + 16)
    }
    this.dataSize = statSync(dataPath).size
    this.fd = openSync(dataPath, "r")
    return usable > 0
  }

  private dataSize = 0

  size(): number {
    return this.ids.length
  }

  private indexOf(id: number): number {
    let low = 0
    let high = this.ids.length - 1
    while (low <= high) {
      const mid = (low + high) >> 1
      const value = this.ids[mid]!
      if (value === id) return mid
      if (value < id) low = mid + 1
      else high = mid - 1
    }
    return -1
  }

  get(id: number): string | undefined {
    if (this.fd === undefined) return undefined
    const i = this.indexOf(id)
    if (i < 0) return undefined
    const length = this.lengths[i]!
    const offset = this.offsets[i]!
    if (offset + length > this.dataSize) return undefined
    const buffer = Buffer.alloc(length)
    readSync(this.fd, buffer, 0, length, offset)
    try {
      return (JSON.parse(buffer.toString("utf-8")) as { text: string }).text
    } catch {
      return undefined
    }
  }

  close(): void {
    if (this.fd !== undefined) closeSync(this.fd)
    this.fd = undefined
  }
}

export function loadContentStore(basePath: string): ContentStore | undefined {
  const store = new ContentStore()
  return store.load(basePath) ? store : undefined
}
